public class Card {
	public string Name; //Used in updatekanbanCardDates(String previosData , String newData)
    public string Id; //Used in updatekanbanCardDates(String previosData , String newData)
    public DateTime DueDate; //Used in updatekanbanCardDates(String previosData , String newData)
    public string ValueStream; //Used in updatekanbanCardDates(String previosData , String newData)
    public string ValueStreamName;
    public string ItemType; //Used in updatekanbanCardDates(String previosData , String newData)
    public string BoardType; //Used in updatekanbanCardDates(String previosData , String newData)
    public Boolean leaf;
    public string ProjectID;
    public string DurationUnits; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal EstimatedDuration; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Priority; //Used in updatekanbanCardDates(String previosData , String newData)
    public string TaskPriority;
    public string GUID; //Used in updatekanbanCardDates(String previosData , String newData)
    public string KanbanCardTemplate;
    public string KanbanCardTemplateName;
    public string OnBudget; //Used in updatekanbanCardDates(String previosData , String newData)
    public string OnQuality; //Used in updatekanbanCardDates(String previosData , String newData)
    public string OnTime; //Used in updatekanbanCardDates(String previosData , String newData)
    public DateTime StartDate; //Used in updatekanbanCardDates(String previosData , String newData)
    public string Title; //Used in updatekanbanCardDates(String previosData , String newData)
    public string Description; //Used in updatekanbanCardDates(String previosData , String newData)
    public string RecordTypeId;
    public string ProjectRoomName;
    public Decimal HarveyBall; //Used in updatekanbanCardDates(String previosData , String newData)
    public string OwnerID; //Used in updatekanbanCardDates(String previosData , String newData)
    public string OwnerName;
    public string WhatName;
    public string WhatID;
    public string Status;
    public integer ChatterCount;
    public List<Attachment> Sticker;
    // New added on Nov-28-2016
    public Decimal Point; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Order; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal EffortRemaining;
    public Boolean SevenDayWorkWeek;
    public datetime CreatedDate;
    public datetime LastModifiedDate;
    public string pointPickList;
    public string CardID; //Used in updatekanbanCardDates(String previosData , String newData)
    public string TemplateID; //Used in updatekanbanCardDates(String previosData , String newData)
    public string CmpID;
    public String JSONDefinition; //Used in updatekanbanCardDates(String previosData , String newData)
    public String JSONData; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ValueStreamCardLink; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ValueStreamLinkID; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ValueStreamCardLinkName;
    public String ValueStreamLinkIDName;
    public String ValueStreamLinkBoardType; //Used in updatekanbanCardDates(String previosData , String newData)
    public String Account; //Used in updatekanbanCardDates(String previosData , String newData)
    public String Contact; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ForceID;
    public String Opportunity; //Used in updatekanbanCardDates(String previosData , String newData)
    public String OpportunityName; //Used in updatekanbanCardDates(String previosData , String newData)
    public String OpportunityStage; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ContactName; //Used in updatekanbanCardDates(String previosData , String newData)
    public String CaseID; //Used in updatekanbanCardDates(String previosData , String newData)
    public String CaseSubject; //Used in updatekanbanCardDates(String previosData , String newData)
    public String CaseStatus; //Used in updatekanbanCardDates(String previosData , String newData)
    public String CasePriority; //Used in updatekanbanCardDates(String previosData , String newData)
    public string ZoneID; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ZoneTitle; //Used in updatekanbanCardDates(String previosData , String newData)
    public String ZoneForceID;
    public String MCForceID;
    public String SWForceID;
    public String LeavedZoneTitle; //Used in updatekanbanCardDates(String previosData , String newData)
    public String LeavedZoneID; //Used in updatekanbanCardDates(String previosData , String newData)
    public String CreateDate;
    public String Extensions;
    public String UrlLink; //Used in updatekanbanCardDates(String previosData , String newData)
    public String AcceptanceCriteria; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Width; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Height; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Top; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Bottom; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Left; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal X; //Used in updatekanbanCardDates(String previosData , String newData)
    public Decimal Y; //Used in updatekanbanCardDates(String previosData , String newData)
    public String resourceId;
    public Decimal percentCompleted;
    public String State;
	public String Color; //Used in updatekanbanCardDates(String previosData , String newData)
	public String AccountName; //Used in updatekanbanCardDates(String previosData , String newData)
    public String AssignToId;
    public String DueDateStatus;
    //KanbanUrl not in class but used
    //SmallPhotoUrl not in class but used
    //Help not in class but used
    //LinkedCardVerb not in class but used
}