/*------------------------------------------------------------
**Copyright 2016-2017 Lucidsoft Inc. All rights reserved.**
Author: 		Dlanyer Ocampo
Company: 		Leankor
Description: 	A class to test KanbanCardJSONUpdator.cls.
				Tests executed:
					1 - updateKanbanCardTest()
					Checks if collection is empty
					2 - updateCardJSONDataTest()
					Checks if collection is empty
					3 - updateCardJSONDataSingularTest()
					Checks if string is not blank
History
010/11/2017		Dlanyer Ocampo	Initial version
------------------------------------------------------------*/
@isTest
private class KanbanCardJSONUpdatorTest {    
   
}