public class TaskData {
	public String Id;
	public String Priority;
	public String OwnerId;
	public String OwnerName;
	public String Subject;
	public String Status;
	public String ActivityDate;
	public String WhatId;
	public String Description;
	public String LinkedCardVerb;
	public String ValueStream;
	public DateTime StartDate;
	public DateTime DueDate;
	public String CreatedDate;
	public String ItemType;
	public String ValueStreamID;
	public String ValueStreamName;
	public String ProjectRoomName;
	public String ProjectRoomID;
	public String SmallPhotoUrl;
	public String KanbanCardName;
	public Boolean expanded;
	public Boolean leaf;
	public String verb;
}